"""Batch C tests: Llama.cpp, Docker Compose, Systemd, Health Check for DGX Spark."""

import json
import os
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
LIB = ROOT / "scripts" / "deploy-dgx-spark-lib.sh"
CLI = ROOT / "scripts" / "deploy-dgx-spark.sh"


def bash(script, env=None):
    """Run a bash script with source LIB pre-loaded."""
    full = f"source {LIB}\n{script}\n"
    merged_env = os.environ.copy()
    if env is not None:
        merged_env.update(env)
    return subprocess.run(
        ["bash", "-c", full],
        capture_output=True, text=True,
        env=merged_env,
        timeout=30,
    )


# ====================================================================
# Batch C.1: Llama.cpp lifecycle scripts
# ====================================================================

def test_start_llama_script_generated():
    """start-llama script is generated by generate_lifecycle_scripts."""
    deploy_root = Path("/tmp/test-batch-c-llama-deploy")
    state_root = Path("/tmp/test-batch-c-llama-state")
    deploy_root.mkdir(exist_ok=True); state_root.mkdir(exist_ok=True)
    try:
        result = bash(f'generate_lifecycle_scripts "{deploy_root}" "{state_root}" "full" "false"')
        assert result.returncode == 0
        start_llama = deploy_root / "bin" / "start-llama"
        assert start_llama.exists(), "start-llama script not generated"
        assert subprocess.run(["bash", "-n", str(start_llama)]).returncode == 0
    finally:
        import shutil
        shutil.rmtree(deploy_root, ignore_errors=True)
        shutil.rmtree(state_root, ignore_errors=True)


def test_stop_llama_script_generated():
    """stop-llama script is generated by generate_lifecycle_scripts."""
    deploy_root = Path("/tmp/test-batch-c-stop-deploy")
    state_root = Path("/tmp/test-batch-c-stop-state")
    deploy_root.mkdir(exist_ok=True); state_root.mkdir(exist_ok=True)
    try:
        result = bash(f'generate_lifecycle_scripts "{deploy_root}" "{state_root}" "full" "false"')
        assert result.returncode == 0
        stop_llama = deploy_root / "bin" / "stop-llama"
        assert stop_llama.exists(), "stop-llama script not generated"
        assert subprocess.run(["bash", "-n", str(stop_llama)]).returncode == 0
    finally:
        import shutil
        shutil.rmtree(deploy_root, ignore_errors=True)
        shutil.rmtree(state_root, ignore_errors=True)


def test_start_llama_exits_2_when_no_gguf_model():
    """start-llama exits with code 2 when no GGUF model is found."""
    deploy_root = Path("/tmp/test-batch-c-nomodel-deploy")
    state_root = Path("/tmp/test-batch-c-nomodel-state")
    deploy_root.mkdir(exist_ok=True); state_root.mkdir(exist_ok=True)
    try:
        result = bash(f'generate_lifecycle_scripts "{deploy_root}" "{state_root}" "full" "false"')
        assert result.returncode == 0
        start_llama = deploy_root / "bin" / "start-llama"
        r = subprocess.run(["bash", str(start_llama)], cwd=ROOT, capture_output=True, text=True, timeout=10)
        assert r.returncode == 2, "expected exit code 2 (no GGUF model found)"
    finally:
        import shutil
        shutil.rmtree(deploy_root, ignore_errors=True)
        shutil.rmtree(state_root, ignore_errors=True)


# ====================================================================
# Batch C.2: Docker Compose generation
# ====================================================================

def test_docker_compose_generated_for_non_minimal():
    """Docker Compose file is generated for non-minimal profiles."""
    deploy_root = Path("/tmp/test-batch-c-dc-deploy")
    state_root = Path("/tmp/test-batch-c-dc-state")
    deploy_root.mkdir(exist_ok=True); state_root.mkdir(exist_ok=True)
    try:
        result = bash(f'generate_docker_compose "{deploy_root}" "full" "true"')
        assert result.returncode == 0
        compose = deploy_root / "docker-compose.yml"
        assert compose.exists(), "docker-compose.yml not generated"
    finally:
        import shutil
        shutil.rmtree(deploy_root, ignore_errors=True)
        shutil.rmtree(state_root, ignore_errors=True)


def test_docker_compose_has_all_services():
    """Generated docker-compose.yml contains all 4 service definitions."""
    deploy_root = Path("/tmp/test-batch-c-svcs-deploy")
    state_root = Path("/tmp/test-batch-c-svcs-state")
    deploy_root.mkdir(exist_ok=True); state_root.mkdir(exist_ok=True)
    try:
        result = bash(f'generate_docker_compose "{deploy_root}" "full" "true"')
        assert result.returncode == 0
        compose = deploy_root / "docker-compose.yml"
        content = compose.read_text()
        assert "comfyui:" in content or "comfyui" in content.lower()
        assert "vllm:" in content or "vllm" in content.lower()
        assert "llama:" in content or "llama" in content.lower()
        assert "piper:" in content or "piper" in content.lower()
    finally:
        import shutil
        shutil.rmtree(deploy_root, ignore_errors=True)
        shutil.rmtree(state_root, ignore_errors=True)


def test_docker_compose_has_health_checks():
    """Generated docker-compose.yml includes health check definitions."""
    deploy_root = Path("/tmp/test-batch-c-hc-deploy")
    state_root = Path("/tmp/test-batch-c-hc-state")
    deploy_root.mkdir(exist_ok=True); state_root.mkdir(exist_ok=True)
    try:
        result = bash(f'generate_docker_compose "{deploy_root}" "full" "true"')
        assert result.returncode == 0
        compose = deploy_root / "docker-compose.yml"
        content = compose.read_text()
        assert "healthcheck:" in content.lower() or "healthcheck" in content.lower()
    finally:
        import shutil
        shutil.rmtree(deploy_root, ignore_errors=True)
        shutil.rmtree(state_root, ignore_errors=True)


def test_docker_compose_has_resource_limits():
    """Generated docker-compose.yml includes resource limits."""
    deploy_root = Path("/tmp/test-batch-c-res-deploy")
    state_root = Path("/tmp/test-batch-c-res-state")
    deploy_root.mkdir(exist_ok=True); state_root.mkdir(exist_ok=True)
    try:
        result = bash(f'generate_docker_compose "{deploy_root}" "full" "true"')
        assert result.returncode == 0
        compose = deploy_root / "docker-compose.yml"
        content = compose.read_text()
        assert "memory:" in content.lower()
    finally:
        import shutil
        shutil.rmtree(deploy_root, ignore_errors=True)
        shutil.rmtree(state_root, ignore_errors=True)


def test_docker_compose_profile_templates_exist():
    """Profile-based compose templates (minimal, media, full) are created."""
    deploy_root = Path("/tmp/test-batch-c-profs-deploy")
    state_root = Path("/tmp/test-batch-c-profs-state")
    deploy_root.mkdir(exist_ok=True); state_root.mkdir(exist_ok=True)
    try:
        result = bash(f'generate_docker_compose "{deploy_root}" "full" "true"')
        assert result.returncode == 0
        config_dir = deploy_root / "config"
        assert (config_dir / "docker-compose.minimal.yml").exists()
        assert (config_dir / "docker-compose.media.yml").exists()
        assert (config_dir / "docker-compose.full.yml").exists()
    finally:
        import shutil
        shutil.rmtree(deploy_root, ignore_errors=True)
        shutil.rmtree(state_root, ignore_errors=True)


def test_docker_compose_no_docker_required():
    """Docker Compose generation works without Docker installed."""
    deploy_root = Path("/tmp/test-batch-c-nodocker-deploy")
    state_root = Path("/tmp/test-batch-c-nodocker-state")
    deploy_root.mkdir(exist_ok=True); state_root.mkdir(exist_ok=True)
    try:
        result = bash(f'generate_docker_compose "{deploy_root}" "full" "false"')
        assert result.returncode == 0
        compose = deploy_root / "docker-compose.yml"
        assert compose.exists()
    finally:
        import shutil
        shutil.rmtree(deploy_root, ignore_errors=True)
        shutil.rmtree(state_root, ignore_errors=True)


# ====================================================================
# Batch C.3: Health check enhancement
# ====================================================================

def test_health_check_script_has_vllm_check():
    """Enhanced health-check script includes vLLM health check."""
    deploy_root = Path("/tmp/test-batch-c-hcv-deploy")
    state_root = Path("/tmp/test-batch-c-hcv-state")
    deploy_root.mkdir(exist_ok=True); state_root.mkdir(exist_ok=True)
    try:
        result = bash(f'generate_lifecycle_scripts "{deploy_root}" "{state_root}" "full" "false"')
        assert result.returncode == 0
        health_check = deploy_root / "bin" / "health-check"
        content = health_check.read_text()
        assert "vllm" in content.lower() or "8000" in content
    finally:
        import shutil
        shutil.rmtree(deploy_root, ignore_errors=True)
        shutil.rmtree(state_root, ignore_errors=True)


def test_health_check_script_has_llama_check():
    """Enhanced health-check script includes llama.cpp health check."""
    deploy_root = Path("/tmp/test-batch-c-hcl-deploy")
    state_root = Path("/tmp/test-batch-c-hcl-state")
    deploy_root.mkdir(exist_ok=True); state_root.mkdir(exist_ok=True)
    try:
        result = bash(f'generate_lifecycle_scripts "{deploy_root}" "{state_root}" "full" "false"')
        assert result.returncode == 0
        health_check = deploy_root / "bin" / "health-check"
        content = health_check.read_text()
        assert "llama" in content.lower() or "8001" in content
    finally:
        import shutil
        shutil.rmtree(deploy_root, ignore_errors=True)
        shutil.rmtree(state_root, ignore_errors=True)


def test_health_check_script_has_piper_check():
    """Enhanced health-check script includes piper health check."""
    deploy_root = Path("/tmp/test-batch-c-hcp-deploy")
    state_root = Path("/tmp/test-batch-c-hcp-state")
    deploy_root.mkdir(exist_ok=True); state_root.mkdir(exist_ok=True)
    try:
        result = bash(f'generate_lifecycle_scripts "{deploy_root}" "{state_root}" "full" "false"')
        assert result.returncode == 0
        health_check = deploy_root / "bin" / "health-check"
        content = health_check.read_text()
        assert "piper" in content.lower() or "5000" in content
    finally:
        import shutil
        shutil.rmtree(deploy_root, ignore_errors=True)
        shutil.rmtree(state_root, ignore_errors=True)


def test_health_check_script_has_healthy_counter():
    """Enhanced health-check script counts healthy services."""
    deploy_root = Path("/tmp/test-batch-c-hcc-deploy")
    state_root = Path("/tmp/test-batch-c-hcc-state")
    deploy_root.mkdir(exist_ok=True); state_root.mkdir(exist_ok=True)
    try:
        result = bash(f'generate_lifecycle_scripts "{deploy_root}" "{state_root}" "full" "false"')
        assert result.returncode == 0
        health_check = deploy_root / "bin" / "health-check"
        content = health_check.read_text()
        assert "healthy_count" in content
    finally:
        import shutil
        shutil.rmtree(deploy_root, ignore_errors=True)
        shutil.rmtree(state_root, ignore_errors=True)


# ====================================================================
# Batch C.4: Systemd orchestration
# ====================================================================

def test_systemd_orchestration_generates_wizard_service():
    """generate_systemd_orchestration creates clawdess-wizard.service."""
    deploy_root = Path("/tmp/test-batch-c-wiz-deploy")
    state_root = Path("/tmp/test-batch-c-wiz-state")
    deploy_root.mkdir(exist_ok=True); state_root.mkdir(exist_ok=True)
    home_backup = os.environ.get("HOME", "")
    home_dir = Path("/tmp/test-batch-c-wiz-home")
    home_dir.mkdir(exist_ok=True)
    os.environ["HOME"] = str(home_dir)
    try:
        result = bash(f'generate_systemd_orchestration "{deploy_root}" "full"')
        assert result.returncode == 0
        systemd_user = home_dir / ".config" / "systemd" / "user"
        wizard = systemd_user / "clawdess-wizard.service"
        assert wizard.exists(), "clawdess-wizard.service not generated"
    finally:
        os.environ["HOME"] = home_backup


def test_systemd_orchestration_generates_ordered_services():
    """Systemd orchestration generates services in correct order."""
    deploy_root = Path("/tmp/test-batch-c-ord-deploy")
    state_root = Path("/tmp/test-batch-c-ord-state")
    deploy_root.mkdir(exist_ok=True); state_root.mkdir(exist_ok=True)
    home_backup = os.environ.get("HOME", "")
    os.environ["HOME"] = str(Path("/tmp/test-batch-c-ord-home"))
    try:
        home_dir = Path(os.environ["HOME"])
        home_dir.mkdir(exist_ok=True)
        result = bash(f'generate_systemd_orchestration "{deploy_root}" "full"')
        assert result.returncode == 0
        systemd_user = home_dir / ".config" / "systemd" / "user"
        comfyui = systemd_user / "clawdess-comfyui.service"
        assert comfyui.exists()
    finally:
        os.environ["HOME"] = home_backup


# ====================================================================
# Batch C.5: State file integration
# ====================================================================

def test_health_check_function_exists():
    """health_check() function is defined in lib.sh."""
    lib_content = LIB.read_text()
    assert "health_check()" in lib_content or "health_check() {" in lib_content


def test_health_check_state_integration():
    """health_check writes running_services and last_health_check to state file."""
    deploy_root = Path("/tmp/test-batch-c-state-deploy")
    state_root = Path("/tmp/test-batch-c-state-state")
    deploy_root.mkdir(exist_ok=True); state_root.mkdir(exist_ok=True)
    (deploy_root / "state").mkdir(exist_ok=True)
    try:
        result = bash(f'health_check "{deploy_root}"')
        # Function exists; exit code may be 1 if no services running
        state_file = deploy_root / "state" / "deployment-state.json"
        if state_file.exists():
            state = json.loads(state_file.read_text())
            assert "running_services" in state or "health_checks" in state or "last_health_check" in state
    finally:
        import shutil
        shutil.rmtree(deploy_root, ignore_errors=True)
        shutil.rmtree(state_root, ignore_errors=True)


# ====================================================================
# Batch C.6: Config — GGUF model entry
# ====================================================================

def test_config_has_gguf_model():
    """dgx-spark-models.json includes llama3-gguf model entry."""
    config = json.loads((ROOT / "config/dgx-spark-models.json").read_text())
    assert "llama3-gguf" in config["models"]
    assert config["models"]["llama3-gguf"]["description"]


def test_config_has_llama_feature():
    """dgx-spark-models.json features list includes 'llama'."""
    config = json.loads((ROOT / "config/dgx-spark-models.json").read_text())
    assert "llama" in config["features"]


def test_config_has_full_profile():
    """dgx-spark-models.json includes 'full' profile with llama feature."""
    config = json.loads((ROOT / "config/dgx-spark-models.json").read_text())
    assert "full" in config["profiles"]
    assert "llama" in config["profiles"]["full"]["features"]


def test_config_has_llama_catalog():
    """dgx-spark-models.json catalog includes llama category."""
    config = json.loads((ROOT / "config/dgx-spark-models.json").read_text())
    assert "llama" in config["catalog"]
    assert "llama3-gguf" in config["catalog"]["llama"]

